apiVersion: v1
kind: Service
metadata:
  name: randomizer-back-service
spec:
  type: NodePort
  selector:
    app: randomizer-back
  ports:
    - name: randomizer-back-port
      protocol: TCP
      port: 31001
---
apiVersion: v1
kind: Service
metadata:
  name: randomizer-front-service
spec:
  type: NodePort
  selector:
    app: randomizer-front
  ports:
    - name: randomizer-front-port
      protocol: TCP
      port: 31002
      targetPort: 80
---
apiVersion: v1
kind: Secret
metadata:
  name: randomizer-secret
type: Opaque
stringData:
  IR_MASTERKEY: "masterkey"
  IR_PORT: "31001"
  IR_ADDRESS: "localhost:5432"
  IR_DB: "postgres"
  IR_SCHEMA: "randomizer"
  IR_USER: "postgres"
  IR_PASSWORD: "random123"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: randomizer-back-deployment
  labels:
    app: randomizer-back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: randomizer-back
  template:
    metadata:
      generateName: randomizer-back-pod-
      labels:
        app: randomizer-back
    spec:
      containers:
        - name: randomizer-back
          image: randomizerback:0.1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 31001
          envFrom:
            - secretRef:
                name: randomizer-secret
---
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: randomizer-front-deployment
    labels:
      app: randomizer-front
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: randomizer-front
    template:
      metadata:
        generateName: randomizer-front-pod-
        labels:
          app: randomizer-front
      spec:
        containers:
          - name: randomizer-front
            image: randomizerfront:0.1.0
            imagePullPolicy: IfNotPresent
            ports:
              - containerPort: 80